### ISSUE TITLE
CzmlDataSource not responding to state changes

### ISSUE THREAD

**Issue by jduncanRadBlue** [darwin-education/resium#223] opened 2020-01-30 18:38 UTC
I have a component that renders czml and the data is set to this.state.czml.  I use redux to update my props and then pass the updated props to my component.  The component tracks the changes and updates its local state to match the props from redux.  The CzmlDataSource seems to ignore changes to the component's local state?  I have the react developer tools and I can see the state is updating as it should in both the props and the local state, but the CzmlDataSource is ignoring these changes.  Is there some sort of setting that needs to be set?  I have attached component code in the next comment below.

**Comment by jduncanRadBlue** [comment] 2020-01-30 18:55
```
import React, {Component} from "react";
import {hot} from "react-hot-loader/root";
import {connect} from "react-redux";
import {Viewer, GeoJsonDataSource, Camera, CameraFlyTo, CzmlDataSource, Entity, PolygonGraphics} from "resium";
import {Cartesian3, Color, Cartesian2} from "cesium";
import {getCZML, clearCZMLData, updateCZML} from "../actions/targetActions";
import PIP from "robust-point-in-polygon";

export class CesiumMap extends Component {
    constructor(props) {
        super(props);
        this.cesium = React.createRef();
        this.state = {
            targetResults: [],
            polygonButtonClicked: false,
            degreesArray: [0,0],
            entities: [],
            showPolygon:false,
            czml: [],
            show: false,
            targetsToKeep: [],
        };

    }

    componentDidMount() {
        const {viewer} = this;
        this.props.getCZML();

        if (viewer) {

        }
    }

    static getDerivedStateFromProps(props, state) {
        let update = {};
        if (props.targets !== state.targetResults) {
            const arrayOfObjects = props.targets.data;

            const uniqueArray = arrayOfObjects.filter((object, index) => index === arrayOfObjects.findIndex(obj => JSON.stringify(obj) === JSON.stringify(object)));
            update.targetResults = uniqueArray;
        }

        if (props.czml.data !== state.czml) {

            const arrayOfCzml = props.czml.data;
            update.czml = arrayOfCzml;
            update.show = true;

        }
        return update;
    }

    getLocationFromScreenXY = (x, y) => {
        //const scene = this.viewer.current?.cesiumElement?.scene;
        const scene = this.viewer.scene
        if (!scene) return;
        const ellipsoid = scene.globe.ellipsoid;
        const cartesian = scene.camera.pickEllipsoid(new Cartesian2(x, y), ellipsoid);
        if (!cartesian) return;
        const {latitude, longitude, height} = ellipsoid.cartesianToCartographic(cartesian);
        return {latitude, longitude, height};
    }

    setPolygonButtonClicked = () => {
        this.setState({polygonButtonClicked: true});
    }

    setClearPolygonButtonClicked = () => {
        this.setState({
            polygonButtonClicked: false,
            degreesArray: [0,0],
            entities: [],
            showPolygon:false,
        })
this.props.clearCZMLData();
this.props.getCZML();
    }

    radiansToDegrees = (radians) => {
        let pi = Math.PI;
        return radians * (180/pi);
    }

    createPolygon = (Object, Entity) => {
        if (this.state.polygonButtonClicked === true) {

            //array is the coordinates array to use for drawing the polygon.
            let array = this.state.degreesArray;
            if (array.includes(0,0)) {
                array.length = 0
            }

            let coords = this.getLocationFromScreenXY(Object.position.x, Object.position.y);
            let lon = this.radiansToDegrees(coords.longitude);
            let lat = this.radiansToDegrees(coords.latitude);
            array.push(lon);
            array.push(lat);
            this.setState({degreesArray: array})

            //entities is an array of objects (entity) that each one represents a point clicked on the map.
            let entities = this.state.entities;
            let entity = [lon,lat]
            entities.push(entity);
            this.setState({entities: entities})

        } else {
            return
        }
    }

    turnOffPolygon = () => {
        this.setState({polygonButtonClicked: false});
    }

    stopDrawing = (Object) => {
        let array = this.state.degreesArray;
        if (array.includes(0,0)) {
            array.length = 0
        }

        let coords = this.getLocationFromScreenXY(Object.position.x, Object.position.y);
        let lon = this.radiansToDegrees(coords.longitude);
        let lat = this.radiansToDegrees(coords.latitude);
        array.push(lon);
        array.push(lat);
        this.setState({degreesArray: array})

        this.setState({polygonButtonClicked: false, showPolygon: true});
        this.filterEntities();
    }

    filterEntities = () => {
        //this.state.entities is the polygon points       

        let polygon = this.state.entities;

        //1 means false, -1 means true...RUn through czml data's entries then
        // pass each point through the PIP function.  if a -1 is returned bold the color or some way to note the inclusion.
        let stateCopy = [...this.state.czml];
        let targetsToKeep = [...this.state.targetsToKeep];
        stateCopy.map((obj, i) => {
            if (obj.position) {
                let array = [];                
                array.push( obj.position.cartographicDegrees[0]);
                array.push(obj.position.cartographicDegrees[1]);               
                let result = PIP(polygon, array)
                console.log(PIP(polygon, array));

                if (result === -1) {
                    obj.ellipse.material.solidColor.color.rgba = [0, 0, 255, 127];
                    obj.ellipse.outline = true;
                    obj.ellipse.outlineColor = {"rgba" : [255, 255, 255, 255] };
                    obj.ellipse.outlineWidth = 3.0;
                    targetsToKeep.push(obj);
                }
            }

            //for whatever reason the update to local state will not work for the czml data.  You have to update the redux state and
            // the component will then realize the change and update the viewer.
            this.props.clearCZMLData();
            this.props.updateCZML(stateCopy);
            this.setState({targetsToKeep})
        });
    }


    render() {
        const polygonButtonClicked = this.state.polygonButtonClicked;
        const showPolygon = this.state.showPolygon;
        let positions;
        if (this.state.degreesArray) {
            positions = Cartesian3.fromDegreesArray(this.state.degreesArray)
        }

        const targetResults = this.state.targetResults;
       
        

        return (
            <Viewer style={{
                width: 'calc(100% - 270px)',
                left: '270px',
                top: '65px',
                height: 'calc(100% - 110px)',
                position: 'fixed'
            }}
                    ref={e => {
                        this.viewer = e ? e.cesiumElement : null;
                    }}
                    onClick={this.createPolygon}
                
            >
                <Camera/>
                <button style={{left: '270px', top: '65px', position: 'fixed'}}
                        onClick={() => this.setPolygonButtonClicked()}>Draw Polygon
                </button>
                <button style={{left: '270px', top: '95px', position: 'fixed'}}
                        onClick={() => this.setClearPolygonButtonClicked()}>Clear Polygon
                </button>
                {showPolygon && (
                    //State is set for polygonButtonClicked to true after it is clicked.  Have the onClick for viewer return an array of clicks only if
                    //setPolygonClicked is true, otherwise return out of function.  Set the hierarcy in the Entity equal to the array of clicks on the viewer.
                    <Entity name="PolygonGraphics" description="PolygonGraphics!!">
                        <PolygonGraphics
                            hierarchy={positions}
                            material={Color.RED.withAlpha(0.28)}
                        />
                    </Entity>
                )}

                {this.state.entities.map((point, index) =>
                    <Entity
                        key={index}
                        name={"polygon Point # "+ (index+1)}
                        description={"polygon Point # "+ (index+1)}
                        position={Cartesian3.fromDegrees(point[0],point[1])}
                        point={{ pixelSize: 10 }}
                        onClick={this.stopDrawing}
                    />
                )
                }                           
                <CzmlDataSource data={this.state.czml} show={this.state.show}/>
            </Viewer>
        );
    }
}

const mapStateToProps = state => ({
    ...state,

})

const mapDispatchToProps = dispatch => ({
    getCZML: () => dispatch(getCZML()),
    clearCZMLData: () => dispatch(clearCZMLData()),
    updateCZML: (data) => dispatch(updateCZML(data))
})

export default hot(connect(mapStateToProps, mapDispatchToProps)(CesiumMap));
```

**Comment by rot1024** [comment] 2020-02-14 06:38
I tried updating `data` prop of CzmlDataSource, but not updated. `show` prop works well. So I guess that the bug is caused by Cesium, not resium.

**Comment by jduncanRadBlue** [comment] 2020-02-26 18:55
Thank you for the work around.  I added the key and the changes are being updated.

**Comment by rot1024** [comment] 2020-07-03 03:08
It may be bug caused by Resium, and it will be fixed in new version: v1.12.

**Comment by rot1024** [comment] 2020-10-15 03:35
Try the latest version of Resium and reopen this issue if the bug persists.

**Closed by rot1024** 2020-10-15 03:35 UTC
Labels: bug, cesium

**Comment by bandaider** [comment] 2023-05-04 13:32
> 

Thank you for the workaround!  Struggled with this for about an hour, wondering if it was my CZML or Resium/Cesium.

**Comment by bitruns** [comment] 2023-06-06 02:59
Similar issue with GeoJsonDataSource. Mapping component to a list of sources, which loads them fine, but when list of sources is removed, GeoJsonDataSource still persists and stores the data.
